Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: Handler
      CodeUri: /Users/csheri/go/src/fuji
      Runtime: go1.x
      Architectures:
        - x86_64